/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeakBankRouteImport } from './routes/_authenticated/weak-bank'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamsNewRouteImport } from './routes/_authenticated/exams.new'
import { Route as AuthenticatedExamsHistoryRouteImport } from './routes/_authenticated/exams.history'
import { Route as AuthenticatedExamsIdRouteImport } from './routes/_authenticated/exams.$id'
import { Route as AuthenticatedExamsIdResultsRouteImport } from './routes/_authenticated/exams.$id.results'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeakBankRoute = AuthenticatedWeakBankRouteImport.update({
  id: '/weak-bank',
  path: '/weak-bank',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsNewRoute = AuthenticatedExamsNewRouteImport.update({
  id: '/exams/new',
  path: '/exams/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsHistoryRoute =
  AuthenticatedExamsHistoryRouteImport.update({
    id: '/exams/history',
    path: '/exams/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsIdRoute = AuthenticatedExamsIdRouteImport.update({
  id: '/exams/$id',
  path: '/exams/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsIdResultsRoute =
  AuthenticatedExamsIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedExamsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/weak-bank': typeof AuthenticatedWeakBankRoute
  '/exams/$id': typeof AuthenticatedExamsIdRouteWithChildren
  '/exams/history': typeof AuthenticatedExamsHistoryRoute
  '/exams/new': typeof AuthenticatedExamsNewRoute
  '/exams/$id/results': typeof AuthenticatedExamsIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/weak-bank': typeof AuthenticatedWeakBankRoute
  '/exams/$id': typeof AuthenticatedExamsIdRouteWithChildren
  '/exams/history': typeof AuthenticatedExamsHistoryRoute
  '/exams/new': typeof AuthenticatedExamsNewRoute
  '/exams/$id/results': typeof AuthenticatedExamsIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/weak-bank': typeof AuthenticatedWeakBankRoute
  '/_authenticated/exams/$id': typeof AuthenticatedExamsIdRouteWithChildren
  '/_authenticated/exams/history': typeof AuthenticatedExamsHistoryRoute
  '/_authenticated/exams/new': typeof AuthenticatedExamsNewRoute
  '/_authenticated/exams/$id/results': typeof AuthenticatedExamsIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/stats'
    | '/weak-bank'
    | '/exams/$id'
    | '/exams/history'
    | '/exams/new'
    | '/exams/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/stats'
    | '/weak-bank'
    | '/exams/$id'
    | '/exams/history'
    | '/exams/new'
    | '/exams/$id/results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/stats'
    | '/_authenticated/weak-bank'
    | '/_authenticated/exams/$id'
    | '/_authenticated/exams/history'
    | '/_authenticated/exams/new'
    | '/_authenticated/exams/$id/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weak-bank': {
      id: '/_authenticated/weak-bank'
      path: '/weak-bank'
      fullPath: '/weak-bank'
      preLoaderRoute: typeof AuthenticatedWeakBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/new': {
      id: '/_authenticated/exams/new'
      path: '/exams/new'
      fullPath: '/exams/new'
      preLoaderRoute: typeof AuthenticatedExamsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/history': {
      id: '/_authenticated/exams/history'
      path: '/exams/history'
      fullPath: '/exams/history'
      preLoaderRoute: typeof AuthenticatedExamsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$id': {
      id: '/_authenticated/exams/$id'
      path: '/exams/$id'
      fullPath: '/exams/$id'
      preLoaderRoute: typeof AuthenticatedExamsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/$id/results': {
      id: '/_authenticated/exams/$id/results'
      path: '/results'
      fullPath: '/exams/$id/results'
      preLoaderRoute: typeof AuthenticatedExamsIdResultsRouteImport
      parentRoute: typeof AuthenticatedExamsIdRoute
    }
  }
}

interface AuthenticatedExamsIdRouteChildren {
  AuthenticatedExamsIdResultsRoute: typeof AuthenticatedExamsIdResultsRoute
}

const AuthenticatedExamsIdRouteChildren: AuthenticatedExamsIdRouteChildren = {
  AuthenticatedExamsIdResultsRoute: AuthenticatedExamsIdResultsRoute,
}

const AuthenticatedExamsIdRouteWithChildren =
  AuthenticatedExamsIdRoute._addFileChildren(AuthenticatedExamsIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedWeakBankRoute: typeof AuthenticatedWeakBankRoute
  AuthenticatedExamsIdRoute: typeof AuthenticatedExamsIdRouteWithChildren
  AuthenticatedExamsHistoryRoute: typeof AuthenticatedExamsHistoryRoute
  AuthenticatedExamsNewRoute: typeof AuthenticatedExamsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedWeakBankRoute: AuthenticatedWeakBankRoute,
  AuthenticatedExamsIdRoute: AuthenticatedExamsIdRouteWithChildren,
  AuthenticatedExamsHistoryRoute: AuthenticatedExamsHistoryRoute,
  AuthenticatedExamsNewRoute: AuthenticatedExamsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
